// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRACTICA03.Models;

namespace PRACTICA03.Migrations
{
    [DbContext(typeof(aplicacioncontext))]
    [Migration("20210525232714_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PRACTICA03.Models.arte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("arteId")
                        .HasColumnType("int");

                    b.Property<int>("muebleId")
                        .HasColumnType("int");

                    b.Property<int>("ropaId")
                        .HasColumnType("int");

                    b.Property<int>("tecnologiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("artes");
                });

            modelBuilder.Entity("PRACTICA03.Models.categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("arteId")
                        .HasColumnType("int");

                    b.Property<int>("muebleId")
                        .HasColumnType("int");

                    b.Property<int?>("mueblesId")
                        .HasColumnType("int");

                    b.Property<int>("ropaId")
                        .HasColumnType("int");

                    b.Property<int>("tecnologiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("arteId");

                    b.HasIndex("mueblesId");

                    b.HasIndex("ropaId");

                    b.HasIndex("tecnologiaId");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("PRACTICA03.Models.muebles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("mueble");
                });

            modelBuilder.Entity("PRACTICA03.Models.ropa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ropas");
                });

            modelBuilder.Entity("PRACTICA03.Models.tecnologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tecnologias");
                });

            modelBuilder.Entity("PRACTICA03.Models.usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("arteId")
                        .HasColumnType("int");

                    b.Property<int?>("categoriaId")
                        .HasColumnType("int");

                    b.Property<int>("muebleId")
                        .HasColumnType("int");

                    b.Property<int>("ropaId")
                        .HasColumnType("int");

                    b.Property<int>("tecnologiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("categoriaId");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("PRACTICA03.Models.categoria", b =>
                {
                    b.HasOne("PRACTICA03.Models.arte", null)
                        .WithMany("categoria")
                        .HasForeignKey("arteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRACTICA03.Models.muebles", null)
                        .WithMany("categoria")
                        .HasForeignKey("mueblesId");

                    b.HasOne("PRACTICA03.Models.ropa", null)
                        .WithMany("categoria")
                        .HasForeignKey("ropaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRACTICA03.Models.tecnologia", null)
                        .WithMany("categoria")
                        .HasForeignKey("tecnologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRACTICA03.Models.usuario", b =>
                {
                    b.HasOne("PRACTICA03.Models.categoria", "categoria")
                        .WithMany("usuario")
                        .HasForeignKey("categoriaId");

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("PRACTICA03.Models.arte", b =>
                {
                    b.Navigation("categoria");
                });

            modelBuilder.Entity("PRACTICA03.Models.categoria", b =>
                {
                    b.Navigation("usuario");
                });

            modelBuilder.Entity("PRACTICA03.Models.muebles", b =>
                {
                    b.Navigation("categoria");
                });

            modelBuilder.Entity("PRACTICA03.Models.ropa", b =>
                {
                    b.Navigation("categoria");
                });

            modelBuilder.Entity("PRACTICA03.Models.tecnologia", b =>
                {
                    b.Navigation("categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
